name: Pipeline

on: [push]

env:
  GO111MODULE: "on"

jobs:
  linter_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: check out code
        uses: actions/checkout@v3

      - name: Integration and unit tests
        run: go test -v -count=1 -race -cover ./...

  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: check out code
        uses: actions/checkout@v3

      - name: install deps
        run: go get .

      - name: build app
        run: go build -o sentinel
